# Generated by Django 5.1 on 2025-11-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(choices=[('bebidas', 'Bebidas'), ('alimentos', 'Alimentos'), ('complementos', 'Complementos')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(choices=[('bebidas', 'Bebidas'), ('alimentos', 'Alimentos'), ('complementos', 'Complementos'), ('otro', 'Otro')], max_length=50)),
                ('sucursal', models.CharField(choices=[('Sucursal 1', 'Sucursal 1'), ('Sucursal 2', 'Sucursal 2')], max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Caffenio.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], max_length=50)),
                ('sucursal', models.CharField(choices=[('Sucursal 1', 'Sucursal 1'), ('Sucursal 2', 'Sucursal 2')], max_length=50)),
                ('empleado', models.CharField(max_length=100)),
                ('productos', models.ManyToManyField(related_name='ventas', to='app_Caffenio.producto')),
            ],
        ),
    ]
