# Generated by Django 5.1 on 2025-11-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Caffenio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Caffenio.proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
    ]
