# Generated by Django 5.1 on 2025-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Caffenio', '0002_venta_proveedor_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
