# Generated by Django 5.2.7 on 2025-11-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Caffenio', '0004_categoria_cliente_empleado_remove_venta_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cafe_caliente', 'Café Caliente'), ('cafe_frio', 'Café Frío'), ('sin_cafe', 'Bebidas Sin Café'), ('alimentos', 'Alimentos'), ('panaderia', 'Panadería'), ('mercancia', 'Mercancía')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
