# Generated by Django 5.2.7 on 2025-11-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Caffenio', '0005_alter_producto_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(choices=[('cafe_caliente', 'Café Caliente'), ('cafe_frio', 'Café Frío'), ('sin_cafe', 'Bebidas Sin Café'), ('alimentos', 'Alimentos'), ('panaderia', 'Panadería'), ('mercancia', 'Mercancía')], max_length=30)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('imagen', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Caffenio.categoria'),
        ),
    ]
