# Generated by Django 5.2.7 on 2025-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Caffenio', '0006_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
